blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.BlogHome.as_view(), name="blog_home"),
    path("<slug:SLUG>/", views.PostDetail.as_view(), name="post_detail"),
]

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home_view"),
    path("about-me/", views.AboutView.as_view(), name="about_view"),
    path("contact-me/", views.ContactView.as_view(), name="contact_view"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("portfolio/", include("portfolio.urls")),
    path("blog/", include("blog.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path("", views.PortfolioHome.as_view(), name="portfolio_home"),
]

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify 

# Create your models here.

class PostCategory(models.Model):
    category = models.CharField(max_length=255)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = ("Post Categories")
        verbose_name_plural = ("Post Categories")
        ordering = ("-timestamp",)

    def __str__(self):
        return self.category


class Post(models.Model):
    post_title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    post_image = models.ImageField(upload_to="post/images")
    post_content = RichTextField()
    category = models.ManyToManyField(PostCategory)
    meta_description = models.CharField(max_length=10000)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = ("Post")
        verbose_name_plural = ("Post")
        ordering = ("-timestamp",)

    def __str__(self):
        return self.post_title

    def snippet(self):
        return self.post_content[:105] + "..."

    def save(self, *args, **kwargs):
        self.slug = slugify(self.post_title)
        super(Post, self).save(*args, **kwargs)

home/models.py
from django.db import models

# Create your models here.

portfolio/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class ProjectType(models.Model):
    project_type = models.CharField(max_length=255)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = ("Project Type")
        verbose_name_plural = ("Project Type")
        ordering = ("-timestamp",)

    def __str__(self):
        return self.project_type


class Portfolio(models.Model):
    project_type = models.ForeignKey(ProjectType, on_delete=models.CASCADE)
    client = models.CharField(max_length=255)
    languages = models.CharField(max_length=255)
    project_image = models.ImageField(upload_to="project/images")
    project_video = models.FileField(upload_to="project/videos", null=True, blank=True)
    preview_link = models.URLField()
    project_description = RichTextField()
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = ("Portfolio")
        verbose_name_plural = ("Portfolio")
        ordering = ("-timestamp",)

    def __str__(self):
        return f"{self.client} Project"

blog/views.py
from django.shortcuts import render
from django.views import View
from .models import Post
from django.core.paginator import Paginator

# Create your views here.

class BlogHome(View):
    def get(self, request, *args, **kwargs):
        all_post = Post.objects.all().order_by("-timestamp")

        p = Paginator(all_post, 15)
        page_number = request.GET.get('page')
        try:
            page_obj = p.get_page(page_number)  # returns the desired page object
        except PageNotAnInteger:
            # if page_number is not an integer then assign the first page
            page_obj = p.page(1)
        except EmptyPage:
            # if page is empty then return last page
            page_obj = p.page(p.num_pages)

        context = {
            "all_post":all_post,
            'page_obj': page_obj
        }
        return render(request, "blog/blog.html", context)


class PostDetail(View):
    def get(self, request, SLUG, *args, **kwargs):
        post = Post.objects.get(slug=SLUG)
        context = {
            "post":post,
        }
        return render(request, "blog/blog-post.html", context)

home/views.py
from django.shortcuts import render
from django.views import View

# Create your views here.

class HomeView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "home/index.html")


class AboutView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "home/about.html")


class ContactView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "home/contact.html")

    def post(self, request, *args, **kwargs):
        name = request.POST.get("name")
        email = request.POST.get("email")
        subject = request.POST.get("subject")
        message = request.POST.get("message")

        res = "Your Message has been sent successfully. I'll respond to you in a bit. Thanks!"
        context = {
            "res":res,
        }
        return render(request, "home/contact.html", context)

portfolio/views.py
from django.shortcuts import render
from django.views import View
from .models import Portfolio

# Create your views here.

class PortfolioHome(View):
    def get(self, request, *args, **kwargs):
        all_portfolio = Portfolio.objects.all().order_by("-timestamp")
        context = {
            "all_portfolio":all_portfolio,
        }
        return render(request, "portfolio/portfolio.html", context)

blog/templates/blog/blog-post.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Saviloper | {{ post.post_title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{ post.meta_description }}">
    <meta name="robots" content="index, follow">
    <meta name="googlebot" content="index, follow">
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Saviloper | {{ post.post_title }}" />
    <meta property="og:description" content="{{ post.meta_description }}" />
    <meta property="og:url" content="https://www.saviloper.com/blog/{{ post.slug}}" />
    <meta property="og:site_name" content="Saviloper: {{ post.post_title }}" />
    <meta property="og:image" content="{% static 'img/mobile_img.jpg' %}" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="Saviloper | {{ post.post_title }}" />
    <meta name="twitter:description" content="{{ post.meta_description }}" />
    <meta name="twitter:image" content="{% static 'img/mobile_img.jpg' %}" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="icon" href="{% static 'img/mobile_img.jpg' %}" type="image/x-icon" />

    <!-- Template Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,600i,700" rel="stylesheet">

    <!-- Template CSS Files -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/preloader.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/circle.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/fm.revealator.jquery.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- CSS Skin File -->
    <link href="{% static 'css/skins/yellow.css' %}" rel="stylesheet">

    <!-- Live Style Switcher - demo only -->
    <link rel="alternate stylesheet" type="text/css" title="blue" href="{% static 'css/skins/blue.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="green" href="{% static 'css/skins/green.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="yellow" href="{% static 'css/skins/yellow.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="blueviolet" href="{% static 'css/skins/blueviolet.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="goldenrod" href="{% static 'css/skins/goldenrod.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="magenta" href="{% static 'css/skins/magenta.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="orange" href="{% static 'css/skins/orange.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="purple" href="{% static 'css/skins/purple.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="red" href="{% static 'css/skins/red.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="yellowgreen" href="{% static 'css/skins/yellowgreen.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/styleswitcher.css' %}" />

    <!-- Modernizr JS File -->
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
</head>

<body class="blog-post">
<!-- Live Style Switcher Starts - demo only -->
<div id="switcher" class="">
    <div class="content-switcher">
        <h4>STYLE SWITCHER</h4>
        <ul>
            <li>
                <a href="#" onclick="setActiveStyleSheet('purple');" title="purple" class="color"><img src="{% static 'img/styleswitcher/purple.png' %}" alt="purple"/></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('red');" title="red" class="color"><img src="{% static 'img/styleswitcher/red.png' %}" alt="red"/></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('blueviolet');" title="blueviolet" class="color"><img src="{% static 'img/styleswitcher/blueviolet.png' %}" alt="blueviolet"/></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('blue');" title="blue" class="color"><img src="{% static 'img/styleswitcher/blue.png' %}" alt="blue"/></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('goldenrod');" title="goldenrod" class="color"><img src="{% static 'img/styleswitcher/goldenrod.png' %}" alt="goldenrod"/></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('magenta');" title="magenta" class="color"><img src="{% static 'img/styleswitcher/magenta.png' %}" alt="magenta"/></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('yellowgreen');" title="yellowgreen" class="color"><img src="{% static 'img/styleswitcher/yellowgreen.png' %}" alt="yellowgreen"/></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('orange');" title="orange" class="color"><img src="{% static 'img/styleswitcher/orange.png' %}" alt="orange"/></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('green');" title="green" class="color"><img src="{% static 'img/styleswitcher/green.png' %}" alt="green"/></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('yellow');" title="yellow" class="color"><img src="{% static 'img/styleswitcher/yellow.png' %}" alt="yellow"/></a>
            </li>
        </ul>

        <div id="hideSwitcher">&times;</div>
    </div>
</div>
<div id="showSwitcher" class="styleSecondColor"><i class="fa fa-cog fa-spin"></i></div>
<!-- Live Style Switcher Ends - demo only -->
<!-- Header Starts -->
<header class="header" id="navbar-collapse-toggle">
    <!-- Fixed Navigation Starts -->
    <ul class="icon-menu d-none d-lg-block revealator-slideup revealator-once revealator-delay1">
        <li class="icon-box">
            <i class="fa fa-home"></i>
            <a href="{% url 'home:home_view' %}">
                <h2>Home</h2>
            </a>
        </li>
        <li class="icon-box">
            <i class="fa fa-user"></i>
            <a href="{% url 'home:about_view' %}">
                <h2>About</h2>
            </a>
        </li>
        <li class="icon-box">
            <i class="fa fa-briefcase"></i>
            <a href="{% url 'portfolio:portfolio_home' %}">
                <h2>Portfolio</h2>
            </a>
        </li>
        <li class="icon-box">
            <i class="fa fa-envelope-open"></i>
            <a href="{% url 'home:contact_view' %}">
                <h2>Contact</h2>
            </a>
        </li>
        <li class="icon-box active">
            <i class="fa fa-comments"></i>
            <a href="{% url 'blog:blog_home' %}">
                <h2>Blog</h2>
            </a>
        </li>
    </ul>
    <!-- Fixed Navigation Ends -->
    <!-- Mobile Menu Starts -->
    <nav role="navigation" class="d-block d-lg-none">
        <div id="menuToggle">
            <input type="checkbox" />
            <span></span>
            <span></span>
            <span></span>
            <ul class="list-unstyled" id="menu">
                <li><a href="{% url 'home:home_view' %}"><i class="fa fa-home"></i><span>Home</span></a></li>
                <li><a href="{% url 'home:about_view' %}"><i class="fa fa-user"></i><span>About</span></a></li>
                <li><a href="{% url 'portfolio:portfolio_home' %}"><i class="fa fa-folder-open"></i><span>Portfolio</span></a></li>
                <li><a href="{% url 'home:contact_view' %}"><i class="fa fa-envelope-open"></i><span>Contact</span></a></li>
                <li class="active"><a href="{% url 'blog:blog_home' %}"><i class="fa fa-comments"></i><span>Blog</span></a></li>
            </ul>
        </div>
    </nav>
    <!-- Mobile Menu Ends -->
</header>
<!-- Header Ends -->
<!-- Page Title Starts -->
<section class="title-section text-left text-sm-center revealator-slideup revealator-once revealator-delay1">
    <h1>my <span>blog</span></h1>
    <span class="title-bg">posts</span>
</section>
<!-- Page Title Ends -->
<!-- Main Content Starts -->
<section class="main-content revealator-slideup revealator-once revealator-delay1">
    <div class="container">
        <div class="row">
            <!-- Article Starts -->
            <article class="col-12">
                <!-- Meta Starts -->
                <div class="meta open-sans-font">
                    <span><i class="fa fa-user"></i> Saviloper</span>
                    <span class="date"><i class="fa fa-calendar"></i> {{ post.timestamp|date:"j F Y" }}</span>
                    <span><i class="fa fa-tags"></i> 
                    {% for i in post.category.all %}
                    {{ i.category }}
                    {% endfor %}
                    </span>
                </div>
                <!-- Meta Ends -->
                <!-- Article Content Starts -->
                <h1 class="text-uppercase text-capitalize">{{ post.post_title }}</h1>
                <img src="{{ post.post_image.url }}" class="img-fluid" alt="Blog image"/>
                <div class="blog-excerpt open-sans-font pb-5">
                    {{ post.post_content|safe }}
                </div>
                <!-- Article Content Ends -->
            </article>
            <!-- Article Ends -->
        </div>
    </div>
</section>
<!-- Template JS Files -->
<script src="{% static 'js/jquery-3.5.0.min.js' %}"></script>
<script src="{% static 'js/styleswitcher.js' %}"></script>
<script src="{% static 'js/preloader.min.js' %}"></script>
<script src="{% static 'js/fm.revealator.jquery.min.js' %}"></script>
<script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'js/masonry.pkgd.min.js' %}"></script>
<script src="{% static 'js/classie.js' %}"></script>
<script src="{% static 'js/cbpGridGallery.js' %}"></script>
<script src="{% static 'js/jquery.hoverdir.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

</body>

</html>

blog/templates/blog/blog.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Saviloper | Modern Developers' Software Development Tips and Tricks</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="You'll find articles, tips, and resources on everything related to software development right here. Everything from coding languages and frameworks to best practices and industry trends is covered. As an experienced software developer, I'm here to assist you in staying current and ahead of the competition.">
    <meta name="robots" content="index, follow">
    <meta name="googlebot" content="index, follow">
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Saviloper | Modern Developers' Software Development Tips and Tricks" />
    <meta property="og:description" content="You'll find articles, tips, and resources on everything related to software development right here. Everything from coding languages and frameworks to best practices and industry trends is covered. As an experienced software developer, I'm here to assist you in staying current and ahead of the competition." />
    <meta property="og:url" content="https://www.saviloper.com/blog/" />
    <meta property="og:site_name" content="Saviloper: Modern Developers' Software Development Tips and Tricks" />
    <meta property="og:image" content="{% static 'img/mobile_img.jpg' %}" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="Saviloper | Modern Developers' Software Development Tips and Tricks" />
    <meta name="twitter:description" content="You'll find articles, tips, and resources on everything related to software development right here. Everything from coding languages and frameworks to best practices and industry trends is covered. As an experienced software developer, I'm here to assist you in staying current and ahead of the competition." />
    <meta name="twitter:image" content="{% static 'img/mobile_img.jpg' %}" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <link rel="icon" href="{% static 'img/mobile_img.jpg' %}" type="image/x-icon" />

    <!-- Template Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,600i,700" rel="stylesheet">

    <!-- Template CSS Files -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/preloader.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/circle.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/fm.revealator.jquery.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- CSS Skin File -->
    <link href="{% static 'css/skins/yellow.css' %}" rel="stylesheet">

    <!-- Live Style Switcher - demo only -->
    <link rel="alternate stylesheet" type="text/css" title="blue" href="{% static 'css/skins/blue.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="green" href="{% static 'css/skins/green.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="yellow" href="{% static 'css/skins/yellow.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="blueviolet" href="{% static 'css/skins/blueviolet.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="goldenrod" href="{% static 'css/skins/goldenrod.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="magenta" href="{% static 'css/skins/magenta.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="orange" href="{% static 'css/skins/orange.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="purple" href="{% static 'css/skins/purple.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="red" href="{% static 'css/skins/red.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="yellowgreen" href="{% static 'css/skins/yellowgreen.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/styleswitcher.css' %}" />

    <!-- Modernizr JS File -->
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
</head>

<body class="blog">
<!-- Live Style Switcher Starts - demo only -->
<div id="switcher" class="">
    <div class="content-switcher">
        <h4>STYLE SWITCHER</h4>
        <ul>
            <li>
                <a href="#" onclick="setActiveStyleSheet('purple');" title="purple" class="color"><img src="{% static 'img/styleswitcher/purple.png' %}" alt="purple"/></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('red');" title="red" class="color"><img src="{% static 'img/styleswitcher/red.png' %}" alt="red"/></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('blueviolet');" title="blueviolet" class="color"><img src="{% static 'img/styleswitcher/blueviolet.png' %}" alt="blueviolet"/></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('blue');" title="blue" class="color"><img src="{% static 'img/styleswitcher/blue.png' %}" alt="blue"/></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('goldenrod');" title="goldenrod" class="color"><img src="{% static 'img/styleswitcher/goldenrod.png' %}" alt="goldenrod"/></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('magenta');" title="magenta" class="color"><img src="{% static 'img/styleswitcher/magenta.png' %}" alt="magenta"/></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('yellowgreen');" title="yellowgreen" class="color"><img src="{% static 'img/styleswitcher/yellowgreen.png' %}" alt="yellowgreen"/></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('orange');" title="orange" class="color"><img src="{% static 'img/styleswitcher/orange.png' %}" alt="orange"/></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('green');" title="green" class="color"><img src="{% static 'img/styleswitcher/green.png' %}" alt="green"/></a>
            </li>
            <li>
                <a href="#" onclick="setActiveStyleSheet('yellow');" title="yellow" class="color"><img src="{% static 'img/styleswitcher/yellow.png' %}" alt="yellow"/></a>
            </li>
        </ul>

        <div id="hideSwitcher">&times;</div>
    </div>
</div>
<div id="showSwitcher" class="styleSecondColor"><i class="fa fa-cog fa-spin"></i></div>
<!-- Live Style Switcher Ends - demo only -->
<!-- Header Starts -->
<header class="header" id="navbar-collapse-toggle">
    <!-- Fixed Navigation Starts -->
    <ul class="icon-menu d-none d-lg-block revealator-slideup revealator-once revealator-delay1">
        <li class="icon-box">
            <i class="fa fa-home"></i>
            <a href="{% url 'home:home_view' %}">
                <h2>Home</h2>
            </a>
        </li>
        <li class="icon-box">
            <i class="fa fa-user"></i>
            <a href="{% url 'home:about_view' %}">
                <h2>About</h2>
            </a>
        </li>
        <li class="icon-box">
            <i class="fa fa-briefcase"></i>
            <a href="{% url 'portfolio:portfolio_home' %}">
                <h2>Portfolio</h2>
            </a>
        </li>
        <li class="icon-box">
            <i class="fa fa-envelope-open"></i>
            <a href="{% url 'home:contact_view' %}">
                <h2>Contact</h2>
            </a>
        </li>
        <li class="icon-box active">
            <i class="fa fa-comments"></i>
            <a href="{% url 'blog:blog_home' %}">
                <h2>Blog</h2>
            </a>
        </li>
    </ul>
    <!-- Fixed Navigation Ends -->
    <!-- Mobile Menu Starts -->
    <nav role="navigation" class="d-block d-lg-none">
        <div id="menuToggle">
            <input type="checkbox" />
            <span></span>
            <span></span>
            <span></span>
            <ul class="list-unstyled" id="menu">
                <li><a href="{% url 'home:home_view' %}"><i class="fa fa-home"></i><span>Home</span></a></li>
                <li><a href="{% url 'home:about_view' %}"><i class="fa fa-user"></i><span>About</span></a></li>
                <li><a href="{% url 'portfolio:portfolio_home' %}"><i class="fa fa-folder-open"></i><span>Portfolio</span></a></li>
                <li><a href="{% url 'home:contact_view' %}"><i class="fa fa-envelope-open"></i><span>Contact</span></a></li>
                <li class="active"><a href="{% url 'blog:blog_home' %}"><i class="fa fa-comments"></i><span>Blog</span></a></li>
            </ul>
        </div>
    </nav>
    <!-- Mobile Menu Ends -->
</header>
<!-- Header Ends -->
<!-- Page Title Starts -->
<section class="title-section text-left text-sm-center revealator-slideup revealator-once revealator-delay1">
    <h1>my <span>blog</span></h1>
    <span class="title-bg">posts</span>
</section>
<!-- Page Title Ends -->
<!-- Main Content Starts -->
<section class="main-content revealator-slideup revealator-once revealator-delay1">
    <div class="container">
        {% if page_obj %}
        <!-- Articles Starts -->
        <div class="row">
            {% for post in page_obj.object_list %}
            <!-- Article Starts -->
            <div class="col-12 col-md-6 col-lg-6 col-xl-4 mb-30">
                <article class="post-container">
                    <div class="post-thumb">
                        <a href="{% url 'blog:post_detail' SLUG=post.slug %}" class="d-block position-relative overflow-hidden">
                            <img src="{{ post.post_image.url }}" class="img-fluid" alt="Blog Post">
                        </a>
                    </div>
                    <div class="post-content">
                        <div class="entry-header">
                            <h3><a href="{% url 'blog:post_detail' SLUG=post.slug %}">{{ post.post_title }}</a></h3>
                        </div>
                        <div class="entry-content open-sans-font">
                            <p>{{ post.snippet|safe }}
                            </p>
                        </div>
                    </div>
                </article>
            </div>
            <!-- Article Ends -->
            {% endfor %}
            <!-- Article Starts -->

            <!-- Pagination Starts -->
            <div class="col-12 mt-4">
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center mb-0">
                        {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                        {% endif %}
                        <li class="page-item active"><a class="page-link" href="#">{{page_obj.number}}</a></li>
                        {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            <!-- Pagination Ends -->
        </div>
        <!-- Articles Ends -->
        {% else %}
        <div class="mt-5 text-center">
            <h3>No Post at the moment</h3>
        </div>
        {% endif %}
    </div>

</section>

<!-- Template JS Files -->
<script src="{% static 'js/jquery-3.5.0.min.js' %}"></script>
<script src="{% static 'js/styleswitcher.js' %}"></script>
<script src="{% static 'js/preloader.min.js' %}"></script>
<script src="{% static 'js/fm.revealator.jquery.min.js' %}"></script>
<script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'js/masonry.pkgd.min.js' %}"></script>
<script src="{% static 'js/classie.js' %}"></script>
<script src="{% static 'js/cbpGridGallery.js' %}"></script>
<script src="{% static 'js/jquery.hoverdir.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

</body>

</html>